services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-ai-app
    env_file:
      - .env
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    

  db:
    image: postgres:${POSTGRES_TAG:-16}
    container_name: project-ai-db
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
